# Form implementation generated from reading ui file 'picard-plugin-persistent-variables/ui_persistent_variables_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets  # noqa: F401


class Ui_PersistentVariablesDialog(object):
    def setupUi(self, PersistentVariablesDialog):
        PersistentVariablesDialog.setObjectName("PersistentVariablesDialog")
        PersistentVariablesDialog.resize(600, 450)
        self.verticalLayout = QtWidgets.QVBoxLayout(PersistentVariablesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.metadata_table = QtWidgets.QTableWidget(parent=PersistentVariablesDialog)
        self.metadata_table.setAutoFillBackground(False)
        self.metadata_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ContiguousSelection)
        self.metadata_table.setRowCount(1)
        self.metadata_table.setColumnCount(2)
        self.metadata_table.setObjectName("metadata_table")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.metadata_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.metadata_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable | QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.metadata_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemFlag.ItemIsSelectable | QtCore.Qt.ItemFlag.ItemIsEnabled)
        self.metadata_table.setItem(0, 1, item)
        self.metadata_table.horizontalHeader().setDefaultSectionSize(150)
        self.metadata_table.horizontalHeader().setSortIndicatorShown(False)
        self.metadata_table.horizontalHeader().setStretchLastSection(True)
        self.metadata_table.verticalHeader().setVisible(False)
        self.metadata_table.verticalHeader().setDefaultSectionSize(20)
        self.metadata_table.verticalHeader().setMinimumSectionSize(20)
        self.verticalLayout.addWidget(self.metadata_table)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=PersistentVariablesDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PersistentVariablesDialog)
        QtCore.QMetaObject.connectSlotsByName(PersistentVariablesDialog)

    def retranslateUi(self, PersistentVariablesDialog):
        _translate = QtCore.QCoreApplication.translate
        item = self.metadata_table.horizontalHeaderItem(0)
        item.setText(_translate("PersistentVariablesDialog", "Variable"))
        item = self.metadata_table.horizontalHeaderItem(1)
        item.setText(_translate("PersistentVariablesDialog", "Value"))
        __sortingEnabled = self.metadata_table.isSortingEnabled()
        self.metadata_table.setSortingEnabled(False)
        self.metadata_table.setSortingEnabled(__sortingEnabled)
